CREATE TABLE `data` (
	`ID` INT(11) NOT NULL AUTO_INCREMENT,
	`TStamp` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	`Temp` FLOAT NOT NULL,
	`Hum` FLOAT NOT NULL,
	PRIMARY KEY (`ID`)
)
ENGINE=InnoDB
;
